# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [2]:
mat1 = np.random.randint(9, size=(3, 3))
mat2 = np.random.randint(9, size=(3, 3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1, .5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[2 0 4]
 [6 4 3]
 [8 3 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 2 0]
 [3 6 1]
 [7 5 8]]

Addition
------------------
 [[10  2  4]
 [ 9 10  4]
 [15  8 16]]

Multiplication
------------------
 [[16  0  0]
 [18 24  3]
 [56 15 64]]

Division
------------------
 [[0.25       0.                inf]
 [2.         0.66666667 3.        ]
 [1.14285714 0.6        1.        ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-10  -4  12]
 [ 12   0   7]
 [ 10  -1   8]]

Addition of a scalar (100)
-------------------------
 [[102 100 104]
 [106 104 103]
 [108 103 108]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  8   0  64]
 [216  64  27]
 [512  27 512]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[1.41421356 0.         2.        ]
 [2.44948974 2.         1.7320508

C:\Users\smilepc\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [11]:
from numpy.random import randint as ri
mat1 = np.array(ri(0,10,9)).reshape(3,3)
mat2 = np.array(ri(0,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=1))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=0))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1, axis=0))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2, axis=1))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(ri(0,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[7 9 1]
 [1 3 0]
 [1 5 2]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 1 3]
 [7 9 4]
 [5 1 6]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 29

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [17  4  8]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 9 17  3]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [  7 135   0]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 12 252  30]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 3.2222222222222223

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [12]:
mat = np.array(ri(0,10,9)).reshape(3,3)
print("Re-shaped matrix is ",mat.reshape(9,1))

Re-shaped matrix is  [[0]
 [9]
 [2]
 [5]
 [3]
 [1]
 [5]
 [2]
 [1]]


### 4.Sort

In [14]:
A = np.array(ri(1,101,10)) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [91 28 41 16 14 26 15 49 31 67]

Here is the sorted vector
 -------------------------------------------------- 
 [14 15 16 26 28 31 41 49 67 91]


In [18]:
M = np.array(ri(0,10,25)).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[7 3 1 6 7]
 [8 2 4 7 0]
 [6 3 8 2 6]
 [5 2 7 8 6]
 [0 8 7 3 4]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[1 3 6 7 7]
 [0 2 4 7 8]
 [2 3 6 6 8]
 [2 5 6 7 8]
 [0 3 4 7 8]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[0 2 1 2 0]
 [5 2 4 3 4]
 [6 3 7 6 6]
 [7 3 7 7 6]
 [8 8 8 8 7]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [32]:
# Fill the following ***** with appropriate solution.
a=np.random.randint(0,100,10)
b=np.random.randint(0,100,10)
c=np.random.randint(0,100,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.where(a==np.max(a)))
print("Max of b location:", np.where(b==np.max(b)))
print("Max of c location:", np.where(c==np.max(c)))

print("Max of a:", np.max(a))
print("Max of b:", np.max(b))


print("Max of a location:", np.where(a==np.max(a)))
print("Max of b location:", np.where(b==np.max(b)))
print("Max of c location:", np.where(c==np.max(c)))



a: [72 98 35 84 81 75  4 54 52  8]
b: [23 86 54 92 90 53  6 93 76 55]
c: [91  4 60 82 69 95  1 28 92 15]
Max of a: 98
Max of b: 93
Max of a location: (array([1], dtype=int64),)
Max of b location: (array([7], dtype=int64),)
Max of c location: (array([5], dtype=int64),)
Max of a: 98
Max of b: 93
Max of a location: (array([1], dtype=int64),)
Max of b location: (array([7], dtype=int64),)
Max of c location: (array([5], dtype=int64),)


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [29]:

mat1 = np.array(ri(0,10,9)).reshape(3,3)
mat2 = np.array(ri(0,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.modf(mat1))



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 8 1]
 [6 1 6]
 [4 9 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[2 9 9]
 [3 5 3]
 [1 7 0]]

Sq-root of 1st matrix using np
------------------
 [[1.73205081 2.82842712 1.        ]
 [2.44948974 1.         2.44948974]
 [2.         3.         1.        ]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[2.00855369e+01 2.98095799e+03 2.71828183e+00]
 [4.03428793e+02 2.71828183e+00 4.03428793e+02]
 [5.45981500e+01 8.10308393e+03 2.71828183e+00]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.47712125 0.90308999 0.        ]
 [0.77815125 0.         0.77815125]
 [0.60205999 0.95424251 0.        ]]

Modulo reminder using np
 -------------------------------------------------- 
 (array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]]), array([[3., 8., 1.],


### 7.Generating matrices from distributions

In [62]:

print("Random number generation (from Uniform distribution)")
print((np.random.uniform(0,1,6)).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print((np.random.normal(0,1,6)).reshape(2,3))


print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.array(ri(0,10,10))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.array(ri(0,7,20))) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.63894632 0.02306674 0.60358792]
 [0.61858589 0.95753108 0.05916147]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.505785    0.0274437   0.9716152 ]
 [-1.18585855 -0.82513979  1.63752705]]
Random integer vector: [43 23 19 83 63 51  7 37 42 64]

Random integer matrix
[4 8 4 3 1 9 2 8 9 9]

20 samples drawn from a dice throw: [1 1 2 1 5 5 5 3 1 4 5 1 0 0 2 4 0 6 2 2]


### 8.Find the nearest value from a given number in an array using NumPy.

In [73]:
#Steps
a=np.array(ri(1,12,5))#Create an array of 5 random element from 1 to 12
print(a)
index = (np.abs(a-10)).argmin()#Suppose find the nearest values of 10 in an array so set value=10
print(index)#find the index where difference is minimum and get the element

[ 8  1 10  5  1]
2


### 9.Write code using numpy to produce following output
[[0 0 0] 
 [0 1 2] 
 [0 2 4]]

In [113]:
l1=[0, 0, 0]
l2=[0, 1 ,2]
l3=[0, 2, 4]
a=np.array([l1,l2,l3])
print(a)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
